<?php
require __DIR__ . '/_common.php';
$post_id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT) ?: filter_input(INPUT_POST, 'id', FILTER_VALIDATE_INT);
if (!$company || !$post_id) { header('Location: posts.php'); exit; }
$message = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
	$title = trim($_POST['title'] ?? ''); $description = trim($_POST['description'] ?? ''); $requirements = trim($_POST['requirements'] ?? ''); $benefits = trim($_POST['benefits'] ?? ''); $location = trim($_POST['location'] ?? ''); $employment_type = $_POST['employment_type'] ?? 'full_time'; $quantity = max(1, (int)($_POST['quantity'] ?? 1)); $deadline = $_POST['deadline'] ?: null; $status = $_POST['status'] ?? 'draft';
	$stmt = $con->prepare('UPDATE internship_posts SET title=?, description=?, requirements=NULLIF(?, ""), benefits=NULLIF(?, ""), location=NULLIF(?, ""), employment_type=?, quantity=?, deadline=?, status=? WHERE id=? AND company_id=?');
	$stmt->bind_param('ssssssissii', $title, $description, $requirements, $benefits, $location, $employment_type, $quantity, $deadline, $status, $post_id, $company['id']);
	if ($stmt->execute()) { header('Location: posts.php'); exit; } $message = 'Không thể cập nhật bài đăng.'; $stmt->close();
}
$stmt = $con->prepare('SELECT title, description, requirements, benefits, location, employment_type, quantity, deadline, status FROM internship_posts WHERE id=? AND company_id=?'); $stmt->bind_param('ii', $post_id, $company['id']); $stmt->execute(); $post = $stmt->get_result()->fetch_assoc(); $stmt->close(); if (!$post) { header('Location: posts.php'); exit; }
company_header('Chỉnh sửa bài đăng');
?><div class="page-title"><h2>Chỉnh sửa bài đăng</h2></div><div class="block"><?php if ($message): ?><p class="upload-message"><?=e($message)?></p><?php endif; ?><form class="profile-form" method="post"><input type="hidden" name="id" value="<?=e($post_id)?>"><label>Tiêu đề vị trí<input class="form-input" name="title" value="<?=e($post['title'])?>" required></label><label>Địa điểm<input class="form-input" name="location" value="<?=e($post['location'])?>"></label><label>Hình thức<input class="form-input" name="employment_type" value="<?=e($post['employment_type'])?>"></label><label>Số lượng<input class="form-input" type="number" name="quantity" min="1" value="<?=e($post['quantity'])?>"></label><label>Hạn nộp<input class="form-input" type="date" name="deadline" value="<?=e($post['deadline'])?>"></label><label>Trạng thái<select class="form-input" name="status"><option value="draft" <?=$post['status'] === 'draft' ? 'selected' : ''?>>Bản nháp</option><option value="published" <?=$post['status'] === 'published' ? 'selected' : ''?>>Đã đăng</option><option value="closed" <?=$post['status'] === 'closed' ? 'selected' : ''?>>Đã đóng</option><option value="cancelled" <?=$post['status'] === 'cancelled' ? 'selected' : ''?>>Đã hủy</option></select></label><label class="profile-form-wide">Mô tả<textarea class="form-input" name="description" rows="6" required><?=e($post['description'])?></textarea></label><label class="profile-form-wide">Yêu cầu<textarea class="form-input" name="requirements" rows="4"><?=e($post['requirements'])?></textarea></label><label class="profile-form-wide">Quyền lợi<textarea class="form-input" name="benefits" rows="4"><?=e($post['benefits'])?></textarea></label><div class="profile-form-actions"><button class="btn" type="submit">Lưu thay đổi</button><a class="btn btn-secondary" href="posts.php">Hủy</a></div></form></div><?php company_footer(); ?>
