<?php
require __DIR__ . '/_common.php';
if (!$company) { header('Location: profile.php'); exit; }
$message = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
	$title = trim($_POST['title'] ?? ''); $description = trim($_POST['description'] ?? ''); $requirements = trim($_POST['requirements'] ?? ''); $benefits = trim($_POST['benefits'] ?? ''); $location = trim($_POST['location'] ?? ''); $employment_type = $_POST['employment_type'] ?? 'full_time'; $quantity = max(1, (int)($_POST['quantity'] ?? 1)); $deadline = $_POST['deadline'] ?: null; $status = $_POST['status'] ?? 'draft';
	$allowed_types = ['full_time', 'part_time', 'remote', 'hybrid']; $allowed_statuses = ['draft', 'published'];
	if ($title === '' || $description === '') $message = 'Vui lòng nhập tiêu đề và mô tả.';
	elseif (!in_array($employment_type, $allowed_types, true) || !in_array($status, $allowed_statuses, true)) $message = 'Dữ liệu bài đăng không hợp lệ.';
	else { $stmt = $con->prepare('INSERT INTO internship_posts (company_id, title, description, requirements, benefits, location, employment_type, quantity, deadline, status) VALUES (?, ?, ?, NULLIF(?, ""), NULLIF(?, ""), NULLIF(?, ""), ?, ?, ?, ?)'); $stmt->bind_param('issssssiss', $company['id'], $title, $description, $requirements, $benefits, $location, $employment_type, $quantity, $deadline, $status); if ($stmt->execute()) { header('Location: posts.php'); exit; } $message = 'Không thể tạo bài đăng.'; $stmt->close(); }
}
company_header('Tạo bài đăng');
?><div class="page-title"><h2>Tạo bài đăng thực tập</h2></div><div class="block"><?php if ($message): ?><p class="upload-message"><?=e($message)?></p><?php endif; ?><form class="profile-form" method="post"><label>Tiêu đề vị trí<input class="form-input" name="title" value="<?=e($_POST['title'] ?? '')?>" required></label><label>Địa điểm<input class="form-input" name="location" value="<?=e($_POST['location'] ?? '')?>"></label><label>Hình thức<select class="form-input" name="employment_type"><option value="full_time">Toàn thời gian</option><option value="part_time">Bán thời gian</option><option value="remote">Từ xa</option><option value="hybrid">Kết hợp</option></select></label><label>Số lượng<input class="form-input" type="number" name="quantity" min="1" value="1"></label><label>Hạn nộp<input class="form-input" type="date" name="deadline"></label><label>Trạng thái<select class="form-input" name="status"><option value="draft">Bản nháp</option><option value="published">Đăng ngay</option></select></label><label class="profile-form-wide">Mô tả<textarea class="form-input" name="description" rows="6" required><?=e($_POST['description'] ?? '')?></textarea></label><label class="profile-form-wide">Yêu cầu<textarea class="form-input" name="requirements" rows="4"><?=e($_POST['requirements'] ?? '')?></textarea></label><label class="profile-form-wide">Quyền lợi<textarea class="form-input" name="benefits" rows="4"><?=e($_POST['benefits'] ?? '')?></textarea></label><div class="profile-form-actions"><button class="btn" type="submit">Lưu bài đăng</button><a class="btn btn-secondary" href="posts.php">Hủy</a></div></form></div><?php company_footer(); ?>
